<?php

namespace CornellCustomDev\LaravelStarterKit\CUAuth\Tests\Feature;

use CornellCustomDev\LaravelStarterKit\CUAuth\Tests\TestCase;
use Illuminate\Contracts\Config\Repository;
use Illuminate\Foundation\Auth\User;
use Illuminate\Support\Str;

class FeatureTestCase extends TestCase
{
    protected function defineEnvironment($app): void
    {
        tap($app['config'], function (Repository $config) {
            // Setup default database to use sqlite :memory:
            $config->set('database.default', 'testbench');
            $config->set('database.connections.testbench', [
                'driver' => 'sqlite',
                'database' => ':memory:',
                'prefix' => '',
            ]);

            // Setup queue database connections.
            $config->set('queue.batching.database', 'testbench');
            $config->set('queue.failed.database', 'testbench');

            // Ensure a valid application encryption key for tests.
            // This must be a base64-encoded 32-byte key as used by Laravel.
            // You can replace the string below with any key generated by `key:generate`.
            $config->set('app.key', 'base64:V0m3Vg7l7wqI2Jwqv1b5JrN8m8m0pJc3n0K8pV9g8zM=');
        });
    }

    protected function defineDatabaseMigrations(): void
    {
        $this->loadLaravelMigrations(['--database' => 'testbench']);
    }

    protected function defineRoutes($router): void
    {
        $router->get('/test', fn () => 'OK')->name('test');
    }

    protected function getTestUser(
        string $name = 'PHPUnit Test User',
        string $email = 'test@example.com',
    ): User {
        $user = new User;
        $user->name = $name;
        $user->email = $email;
        $user->password = Str::random(32);

        return $user;
    }
}
